In [18]:
import numpy as np
P = [[0.9,0.1,0,0],
    [0, 0, 0.5,0.5],
    [0, 0, 0.9, 0.1],
    [0, 0.1, 0, 0.9]]

In [19]:
P = np.array(P)

In [20]:
def steady_state_power(transition_matrix):
    matrix_itr = np.linalg.matrix_power(transition_matrix, 500)
    a = matrix_itr
    return a
print(steady_state_power(P))
    

[[1.32207082e-23 6.25000000e-02 3.12500000e-01 6.25000000e-01]
 [0.00000000e+00 6.25000000e-02 3.12500000e-01 6.25000000e-01]
 [0.00000000e+00 6.25000000e-02 3.12500000e-01 6.25000000e-01]
 [0.00000000e+00 6.25000000e-02 3.12500000e-01 6.25000000e-01]]
