In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np
import math
import pandas as pd
import pprint

data_raw = pd.read_csv('flowers.csv')
remove_categorical = ["species"]
dataset = data_raw.drop(columns = remove_categorical)
features = dataset.columns
data_npy = dataset.to_numpy()

# breast = load_breast_cancer()
# features = breast.feature_names
# breast_data = breast.data

# dataset = pd.DataFrame(breast_data)
# dataset.columns = features

std_sklr = StandardScaler()
x = std_sklr.fit_transform(X = data_npy)
pca_data = PCA(n_components=len(features))
norm_principalComponents_data = pca_data.fit_transform(x)
eigen_values = pca_data.explained_variance_ratio_
print(eigen_values)

def get_data():
    scree_plot = {}
    eigen_total = sum(eigen_values)
    variance_percentage = []
    for i in  eigen_values:
        variance_percentage.append((i/eigen_total)*100)
    
    cumulative_variance = []
    temp = 0
    for i in variance_percentage:
        temp += i
        cumulative_variance.append(temp)
 
    for i in range(0, len(eigen_values)):
        scree_plot[i+1] = {"variance_percentage" : variance_percentage[i], "cumulative_variance": cumulative_variance[i]}
    return scree_plot

def get_top_pca():
    data_send = {}
    count = 0
    for i, j, k in zip(features, pca_data.components_[0], pca_data.components_[1]):
        data_send[count] = {}
        data_send[count]["name"] = i
        data_send[count]["pc1"] = j
        data_send[count]["pc2"] = k
        count += 1
    return data_send

def get_top_four_features(di = 3):
    squared_value = pca_data.components_[:di] ** 2

    features_dict = {}
    for i in range(0, len(squared_value[0])):
        total = 0
        for j in range(0, len(squared_value)):
            total += squared_value[j][i]
        features_dict[features[i]] = math.sqrt(total)

    sorted_features_dict = [k for k, v in sorted(features_dict.items(), key=lambda item: item[1])]
    sorted_features_dict = sorted_features_dict[::-1]
    best_four_features = sorted_features_dict[:4]
    
    temp = best_four_features
    
    values_best_best_four_features = {}
    for i in best_four_features:
        values_best_best_four_features[i] = features_dict[i]

    return values_best_best_four_features

def get_top_four_matrix(di = 3):
    imp_features = get_top_four_features(di)
    imp_features_arr = [i for i in imp_features]
    np_data = dataset[imp_features_arr].to_numpy()
    
    cluster_features = [i for i in imp_features]
    featured_data = dataset[cluster_features]
    kmeans = KMeans(n_clusters=2, random_state=0).fit(featured_data)
    
    send_data = {}
    for i in range(0, np_data.shape[0]):
        send_data[i] = {}
        for j in range(0, len(imp_features_arr)):
            send_data[i][imp_features_arr[j]] = np_data[i][j]
        send_data[i]["label"] = kmeans.labels_[i]

    pprint.pprint(send_data)
    return send_data

get_top_four_matrix()

[0.72962445 0.22850762 0.03668922 0.00517871]


NameError: name 'KMeans' is not defined

In [6]:
pca_data.components_[0:3]

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274]])

In [48]:
kmeans.labels_[0]

0

In [45]:
kmeans.cluster_centers_

array([[3.36981132, 5.00566038, 0.29056604, 1.56037736],
       [2.88659794, 6.30103093, 1.69587629, 4.95876289]])

In [64]:
most_important

[7, 9, 11, 21, 4, 28, 29, 14, 16, 8]

In [75]:
features = breast.feature_names
features.shape

(569,)

In [83]:
for i in features:
    print(i)

mean radius
mean texture
mean perimeter
mean area
mean smoothness
mean compactness
mean concavity
mean concave points
mean symmetry
mean fractal dimension
radius error
texture error
perimeter error
area error
smoothness error
compactness error
concavity error
concave points error
symmetry error
fractal dimension error
worst radius
worst texture
worst perimeter
worst area
worst smoothness
worst compactness
worst concavity
worst concave points
worst symmetry
worst fractal dimension


In [96]:
data_send = {}
count = 0
for i, j, k in zip(features, pca_breast.components_[0], pca_breast.components_[1]):
    data_send[count] = {}
    data_send[count]["name"] = i
    data_send[count]["pc1"] = j
    data_send[count]["pc2"] = k
    count += 1

In [97]:
data_send

{0: {'name': 'mean radius',
  'pc1': 0.21890244370001577,
  'pc2': -0.233857131747535},
 1: {'name': 'mean texture',
  'pc1': 0.10372457821567597,
  'pc2': -0.05970608829080295},
 2: {'name': 'mean perimeter',
  'pc1': 0.2275372930056408,
  'pc2': -0.21518136139684982},
 3: {'name': 'mean area',
  'pc1': 0.22099498538594436,
  'pc2': -0.23107671128362745},
 4: {'name': 'mean smoothness',
  'pc1': 0.14258969436025495,
  'pc2': 0.18611302267032268},
 5: {'name': 'mean compactness',
  'pc1': 0.23928535395301204,
  'pc2': 0.15189161007283025},
 6: {'name': 'mean concavity',
  'pc1': 0.25840048124874004,
  'pc2': 0.0601653627989567},
 7: {'name': 'mean concave points',
  'pc1': 0.26085375838568264,
  'pc2': -0.03476750049364384},
 8: {'name': 'mean symmetry',
  'pc1': 0.13816695930365536,
  'pc2': 0.19034877037208467},
 9: {'name': 'mean fractal dimension',
  'pc1': 0.06436334637180302,
  'pc2': 0.3665754713785027},
 10: {'name': 'radius error',
  'pc1': 0.20597877585522775,
  'pc2': -0.105